#Ambient Sounds
#The mod is no longer maintained for version 1.20, so we need a mixin to make the sounds work properly during snowfall.
[ambientsounds]
	Enable = true

#Presence Footsteps
[presencefootsteps]
	Enable = true

#Journey Map
[journeymap]
	Enable = true

#Particle Rain
[particlerain]
	Enable = true
	#When it rains in desert biomes, replace it with a sandstorm.
	FixSand = true
