version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
modularforcefields = true
azurelib = true
fastitemframes = true
mcwfences = true
farmersdelight = true
upgrade_aquatic = true
mcwbyg = true
cookingforblockheads = true
excavated_variants = true
environmental = true
er2create = true
mcwstairs = true
clayworks = true
friendsandfoes = true
easyanvils = true
refurbished_furniture = true
copycats = true
atmospheric = true
furniture = true
comforts = true
irons_jewelry = true
sootychimneys = true
abnormals_delight = true
immersive_furniture = false
mcwbridges = true
simpleplanes = true
magistuarmory = true
craftingstation = true
handcrafted = true
jaopca = true
wider_ender_chests = true
snowrealmagic = true
chisel = true
voltaic = true
dawnoftimebuilder = false
drill_drain = true
waterframes = true
exposure = true
knightlib = true
rftoolsstorage = true
chiselsandbits = true
rftoolsutility = true
supplementaries = true
l2complements = true
createrailwaysnavigator = true
endrem = true
industrialforegoing = true
woodworks = true
rftoolsbase = true
pastel = true
culturaldelights = true
create = true
rottencreatures = true
items_displayed = true
databank = true
flowerseeds2 = true
wormhole = true
additionallanterns = true
hexerei = true
biomeswevegone = true
visualworkbench = true
ballistix = true
rftoolsbuilder = true
minecraft = true
hearth_and_timber = true
fdlib = true
fdbosses = true
createaddition = true
creeperoverhaul = true
mcwfurnitures = true
dragonlib = true
travelersbackpack = true
sophisticatedstorage = true
rftoolspower = true
enderstorage = true
manyideas_core = true
sliceanddice = true
display_case = true
additional_lights = true
ironfurnaces = true
bigreactors = true
immersiveengineering = false
born_in_chaos_v1 = true
createnuclear = true
disenchanting_table = true
candlelight = true
mcwroofs = true
alexsmobs = true
mcwwindows = true
easymagic = true
securitycraft = true
cataclysm = true
another_furniture = true
irons_spellbooks = true
additionalplacements = true
mcwabnormals = true
diagonalwalls = true
stoneworks = true
citadel = true
nuclearscience = true
mcwpaths = true
create_sa = true
fastpaintings = true
mcwtrpdoors = true
mekanismgenerators = true
bellsandwhistles = true
eidolon_repraised = true
amendments = true
electrodynamics = true
eclipticseasons = true
diagonalfences = true
moonlight = true
bakery = true
sophisticatedbackpacks = true
treechop = true
netherchested = true
mekanismadditions = true
mcwdoors = true
incubation = true
manyideas_doors = true
suppsquared = true
chipped = true
tfmg = true
mekanism = true
immersivepetroleum = false
farm_and_charm = true
legendarysurvivaloverhaul = true
trashcans = true
ironchest = true
displaydelight = true
iceandfire = true
dynamicelectricity = true
createdeco = true
endermanoverhaul = true
ae2 = true
platforms = true
decorative_blocks = true
monolib = true
oritech = true
l2hostility = true
enchantinginfuser = true
rechiseled = true
enderio = true
