#General settings
[General]
	#Determines the spoilrate in specific containers [Syntax: tileentity:spoil_rate]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#"cookingforblockheads:fridge,0.2" would make a cooking for blockheads fridge spoil at 20% of the usual spoilrate
	containerModifier = ["minecraft:shulker_box,0", "refurbished_furniture:light_fridge,0", "refurbished_furniture:dark_fridge,0", "cookingforblockheads:fridge,0"]
	#Determines the spoilrate in specific item containers [Syntax: modid:item_id]
	#Examples: "minecraft:shulker_box,0" would make shulker boxes not spoil food
	#
	itemContainerModifier = ["minecraft:shulker_box,0", "refurbished_furniture:light_fridge,0", "refurbished_furniture:dark_fridge,0", "cookingforblockheads:white_fridge,0", "cookingforblockheads:orange_fridge,0", "cookingforblockheads:magenta_fridge,0", "cookingforblockheads:light_blue_fridge,0", "cookingforblockheads:yellow_fridge,0", "cookingforblockheads:lime_fridge,0", "cookingforblockheads:pink_fridge,0", "cookingforblockheads:gray_fridge,0", "cookingforblockheads:light_gray_fridge,0", "cookingforblockheads:cyan_fridge,0", "cookingforblockheads:purple_fridge,0", "cookingforblockheads:blue_fridge,0", "cookingforblockheads:brown_fridge,0", "cookingforblockheads:green_fridge,0", "cookingforblockheads:red_fridge,0", "cookingforblockheads:black_fridge,0"]
	#Defines the default total amount of spoiling updates for each food item 
	#(For example, a defaultSpoilTime of 40 means any default food item will have 40 total updates before it spoils. 
	#This can be altered when custom food spoiling is set using a datapack) [default: 30]
	# Default: 30
	# Range: > 1
	spoilRate = 100
	#When enabled Spoiled initializes spoiling for all vanilla food [default: true]
	initializeSpoiling = true
	#When enabled enables a special recipe to merge spoiling food together [default: false]
	mergeSpoilingFood = true
	#When enabled Spoiled makes every edible item spoil into the specified Spoil Item (This overwrites json spoiling completely) [default: false]
	spoilEverything = true
	#Defines a list of items that are never allowed to spoil
	spoilBlacklist = ["minecraft:rotten_flesh", "minecraft:enchanted_golden_apple", "minecraft:golden_apple", "oritech:biomass", "supplementaries:candy", "rottencreatures:magma_rotten_flesh", "minecraft:spider_eye", "rottencreatures:frozen_rotten_flesh", "minecraft:golden_carrot", "minecraft:poisonous_potato", "minecraft:dried_kelp", "born_in_chaos_v1:rotten_fish", "farm_and_charm:rotten_tomato", "minecraft:honey_bottle", "minecraft:ominous_bottle"]
	#Defines the total amount of spoiling updates that is used by the default initialized spoiling when 'initializeSpoiling' is enabled 
	#(If the 'spoilRate' is 10 and the 'defaultSpoilTime' is set to 20 then the food will spoil after 20 * 10 seconds = 200 seconds) [default: 40]
	# Default: 40
	# Range: > 1
	defaultSpoilTime = 108
	#Defines the item the foods vanilla foods will turn into when spoiled (if empty it will clear the spoiling item) [default: 'minecraft:rotten_flesh']
	defaultSpoilItem = "oritech:biomass"
